name: robocarrera
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_joystick: ^0.0.4
  go_router: ^14.0.0
  shared_preferences: ^2.0.6
  vibration: ^1.8.4
  window_size: # plugin is not yet part of the flutter framework
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.2.0

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SpecialElite
      fonts:
        - asset: fonts/SpecialElite-Regular.ttf
